config/routes.rb
MLBay::Application.routes.draw do
  resources :algorithms do
    member do
      get 'classify'
    end
  end

end

app/models/algorithm.rb
class Algorithm < ActiveRecord::Base
  attr_accessible :algorithm, :data, :name, :file
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :api_key, :email, :password
end

app/controllers/algorithms_controller.rb
class AlgorithmsController < ApplicationController
  # GET /algorithms
  # GET /algorithms.json
  require 'java'
  require 'json'
  import 'weka.classifiers'
  import 'weka.classifiers.functions'
  include_class "weka.classifiers.Classifier"
  include_class "java.io.FileReader"
  include_class "weka.core.Instances"
  include_class "weka.core.Instance"
  include_class "weka.core.Attribute"
  include_class "weka.core.xml.XMLSerialization"
  include_class "java.io.BufferedReader"
  include_class "weka.classifiers.xml.XMLClassifier"
  
  def index
    @algorithms = Algorithm.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @algorithms }
    end
  end

  # GET /algorithms/1
  # GET /algorithms/1.json
  def show
    @algorithm = Algorithm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @algorithm }
    end
  end

  # GET /algorithms/new
  # GET /algorithms/new.json
  def new
    @algorithm = Algorithm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @algorithm }
    end
  end

  # GET /algorithms/1/edit
  def edit
    @algorithm = Algorithm.find(params[:id])
  end

  # POST /algorithms
  # POST /algorithms.json
  def create
    file_name = Rails.root.join('public/autoPrice.arff').to_s
    file = FileReader.new(file_name)
    train_data = Instances.new file
    train_data.set_class_index(train_data.num_attributes() - 1)
    case params[:algorithm][:algorithm]
    when 'LinearRegression'
      classifier = LinearRegression.new
    when 'SimpleLinearRegression'
      classifier = SimpleLinearRegression.new
    when 'SMO'
      classifier = SMO.new
    when 'SMOreg'
      classifier = SMOreg.new
    when 'VotedPerceptron'
      classifier = VotedPerceptron.new
    else
      classifier = LinearRegression.new
    end
    classifier.build_classifier train_data
    debugger
    params[:algorithm][:data] = Marshal.dump(classifier)
    params[:algorithm][:file] = file_name
    @algorithm = Algorithm.new(params[:algorithm])
    respond_to do |format|
      if @algorithm.save
        format.html { redirect_to @algorithm, notice: 'Algorithm was successfully created.' }
        format.json { render json: @algorithm, status: :created, location: @algorithm }
      else
        format.html { render action: "new" }
        format.json { render json: @algorithm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /algorithms/1
  # PUT /algorithms/1.json
  def update
    @algorithm = Algorithm.find(params[:id])

    respond_to do |format|
      if @algorithm.update_attributes(params[:algorithm])
        format.html { redirect_to @algorithm, notice: 'Algorithm was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @algorithm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /algorithms/1
  # DELETE /algorithms/1.json
  def destroy
    @algorithm = Algorithm.find(params[:id])
    @algorithm.destroy

    respond_to do |format|
      format.html { redirect_to algorithms_url }
      format.json { head :no_content }
    end
  end
  
  def classify
    algorithm = Algorithm.find(params[:id])
    classifier = Marshal.load(algorithm.data)
    file = FileReader.new(algorithm.file)
    train_data = Instances.new file
    train_data.set_class_index(train_data.num_attributes() - 1)
    arr = JSON.parse params[:instance]
    inst = train_data.first_instance.copy
    inst.enumerate_attributes.each_with_index do |attr,i|
      inst.set_value i,arr[i]
    end
    @result = classifier.classify_instance(inst)
    respond_to do |format|
      format.json {render :json => @result}
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  require 'java'
  import 'weka.classifiers.functions'
  include_class "java.io.FileReader"
  include_class "weka.core.Instances"
  include_class "weka.core.Instance"
  include_class "weka.core.Attribute"

  def index
    file = FileReader.new(Rails.root.join('public/autoPrice.arff').to_s)
    data = Instances.new file
    data.set_class_index(data.num_attributes() - 1)
    regress = SimpleLinearRegression.new
    regress.build_classifier data
    arr = [2,164,99.8,176.6,66.2,54.3,2337,109,3.19,3.4,10,102,5500,24,30,13950]
    inst = data.first_instance.copy
    inst.enumerate_attributes.each_with_index do |attr,i|
      inst.set_value i,arr[i]
    end
    regress.classify_instance inst
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/algorithms_helper.rb
module AlgorithmsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/algorithms/_form.html.erb
<%= form_for(@algorithm) do |f| %>
  <% if @algorithm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@algorithm.errors.count, "error") %> prohibited this algorithm from being saved:</h2>

      <ul>
      <% @algorithm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :algorithm %><br />
    <%= f.text_field :algorithm %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_field :data %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/algorithms/edit.html.erb
<h1>Editing algorithm</h1>

<%= render 'form' %>

<%= link_to 'Show', @algorithm %> |
<%= link_to 'Back', algorithms_path %>

app/views/algorithms/index.html.erb
<h1>Listing algorithms</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Algorithm</th>
    <th>Data</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @algorithms.each do |algorithm| %>
  <tr>
    <td><%= algorithm.name %></td>
    <td><%= algorithm.algorithm %></td>
    <td><%= algorithm.data %></td>
    <td><%= link_to 'Show', algorithm %></td>
    <td><%= link_to 'Edit', edit_algorithm_path(algorithm) %></td>
    <td><%= link_to 'Destroy', algorithm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Algorithm', new_algorithm_path %>

app/views/algorithms/new.html.erb
<h1>New algorithm</h1>

<%= render 'form' %>

<%= link_to 'Back', algorithms_path %>

app/views/algorithms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @algorithm.name %>
</p>

<p>
  <b>Algorithm:</b>
  <%= @algorithm.algorithm %>
</p>

<p>
  <b>Data:</b>
  <%= @algorithm.data %>
</p>


<%= link_to 'Edit', edit_algorithm_path(@algorithm) %> |
<%= link_to 'Back', algorithms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MLBay</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :api_key %><br />
    <%= f.text_field :api_key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Password</th>
    <th>Api key</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= user.api_key %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Api key:</b>
  <%= @user.api_key %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>